
//object containing words along with their category
export const words2guess = {
    //Animals
    "elephant": "animal",
    "penguin": "animal",
    "giraffe": "animal",
    "dolphin": "animal",
    "kangaroo": "animal",
    "rhinoceros": "animal",
    "octopus": "animal",
    "tarantula": "animal",
    "salamander": "animal",
    "chameleon": "animal",

    //Musical Instruments
    "piano": "musical instrument",
    "guitar": "musical instrument",
    "violin": "musical instrument",
    "trumpet": "musical instrument",
    "saxophone": "musical instrument",
    "drums": "musical instrument",
    "harp": "musical instrument",
    "cello": "musical instrument",
    "flute": "musical instrument",

    //Vehicles
    "bicycle": "vehicle",
    "motorcycle": "vehicle",
    "aeroplane": "vehicle",
    "submarine": "vehicle",
    "helicopter": "vehicle",
    "scooter": "vehicle",
    "space ship": "vehicle",
    "yacht": "vehicle",
    "skate board": "vehicle",
    "mini van": "vehicle",

    //Fruits
    "avocado": "fruit",
    "pineapple": "fruit",
    "pomegranate": "fruit",
    "strawberry": "fruit",
    "blueberry": "fruit",
    "watermelon": "fruit",
    "grape fruit": "fruit",
    "mango": "fruit",
    "blackberry": "fruit",
    "kiwi": "fruit",
    "papaya": "fruit",
    "banana": "fruit",

    //Vegetables
    "broccoli": "vegetable",
    "spinach": "vegetable",
    "cucumber": "vegetable",
    "cauliflower": "vegetable",
    "zucchini": "vegetable",
    "carrot": "vegetable",
    "asparagus": "vegetable",
    "egg plant": "vegetable",
    "lettuce": "vegetable",
    "onion": "vegetable",

    //Gemstones
    "aventurine": "gemstone",
    "opal": "gemstone",
    "sapphire": "gemstone",
    "emerald": "gemstone",
    "ruby": "gemstone",
    "topaz": "gemstone",
    "amethyst": "gemstone",
    "turquoise": "gemstone",
    "jade": "gemstone",
    "amber": "gemstone",
    "pearl": "gemstone",
    "diamond": "gemstone",

    //Programming Languages
    "python": "programming language",
    "java script": "programming language",
    "ruby": "programming language",
    "java": "programming language",
    "kotlin": "programming language",
    "php": "programming language",
    "html": "programming language",
    "css": "programming language",
    "rust": "programming language",
    "assembly": "programming language",

    //Countries
    "brazil": "country",
    "canada": "country",
    "japan": "country",
    "egypt": "country",
    "italy": "country",
    "australia": "country",
    "nigeria": "country",
    "germany": "country",
    "mexico": "country",
    "india": "country",

    //Sports
    "basket ball": "sport",
    "soccer": "sport",
    "tennis": "sport",
    "cricket": "sport",
    "base ball": "sport",
    "hockey": "sport",
    "volley ball": "sport",
    "golf": "sport",
    "badminton": "sport",
    "rugby": "sport",

    //Occupations
    "doctor": "occupation",
    "engineer": "occupation",
    "teacher": "occupation",
    "artist": "occupation",
    "chef": "occupation",
    "fire fighter": "occupation",
    "lawyer": "occupation",
    "architect": "occupation",
    "plumber": "occupation",
    "dentist": "occupation",

    //Tools
    "hammer": "tool",
    "wrench": "tool",
    "screw driver": "tool",
    "drill": "tool",
    "saw": "tool",
    "chisel": "tool",
    "shovel": "tool",
    "ruler": "tool",
};